# Generated by Django 5.1.14 on 2025-12-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.CharField(blank=True, max_length=256)),
                ("publicationDate", models.DateField()),
                ("cover_image", models.ImageField(null=True, upload_to="events/")),
                ("location", models.CharField(max_length=256)),
            ],
        ),
    ]
