# Generated by Django 5.1.14 on 2025-12-05 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="date",
            field=models.DateField(default="2025-12-05"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="startTime",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
