# Generated by Django 5.1.14 on 2025-12-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_date_event_starttime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="startTime",
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
