# Generated by Django 5.1.14 on 2025-11-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('profile_picture', models.ImageField(null=True, upload_to='profiles/')),
                ('about', models.CharField(blank=True, max_length=256)),
                ('pronouns', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
