# Generated by Django 5.1.14 on 2025-11-29 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_dev", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=4500)),
            ],
        ),
        migrations.CreateModel(
            name="Games",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=4500)),
                (
                    "completion",
                    models.IntegerField(
                        choices=[
                            (1, "Work in Progress (Unplayable)"),
                            (2, "Playable - In Development"),
                            (3, "Beta - Stable but not Final"),
                            (4, "Completed"),
                        ],
                        default=1,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("hostURL", models.CharField(max_length=2083)),
                ("isItch", models.BooleanField(default=True)),
                ("pathToMedia", models.CharField(max_length=2083)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game_dev.events",
                    ),
                ),
            ],
        ),
    ]
