# Generated by Django 5.1.14 on 2026-01-09 13:31

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_dev", "0002_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="date",
            field=models.DateTimeField(
                db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "completion",
                    models.IntegerField(
                        choices=[
                            (1, "Work in Progress (Unplayable)"),
                            (2, "Playable - In Development"),
                            (3, "Beta - Stable but not Final"),
                            (4, "Completed"),
                        ],
                        default=1,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "hostURL",
                    models.CharField(
                        help_text="If game is stored on itch.io, please enter the 7 digit long game id as its hostURL, i.e., 1000200",
                        max_length=2083,
                    ),
                ),
                ("isItch", models.BooleanField(default=True)),
                ("pathToThumbnail", models.ImageField(null=True, upload_to="games/")),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="game_dev.event",
                    ),
                ),
            ],
        ),
    ]
