# Generated by Django 5.1.14 on 2025-12-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_dev", "0002_events_games"),
    ]

    operations = [
        migrations.AddField(
            model_name="games",
            name="itchEmbeddedID",
            field=models.PositiveIntegerField(default=None),
        ),
    ]
