# Generated by Django 5.1.14 on 2025-12-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_dev", "0002_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
