# Generated by Django 5.1.14 on 2025-12-06 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_dev", "0003_games_itchembeddedid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="games",
            name="itchEmbeddedID",
        ),
        migrations.AlterField(
            model_name="games",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="game_dev.events",
            ),
        ),
        migrations.AlterField(
            model_name="games",
            name="hostURL",
            field=models.CharField(
                help_text="If game is stored on itch.io, please enter the 7 digit long game id as its hostURL, i.e., 1000200",
                max_length=2083,
            ),
        ),
        migrations.AlterField(
            model_name="games",
            name="pathToMedia",
            field=models.ImageField(null=True, upload_to="games/[id]/"),
        ),
    ]
