# Generated by Django 5.1.14 on 2025-12-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_dev", "0003_event_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
