# Generated by Django 5.1.14 on 2026-01-10 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_dev", "0003_event_date_game"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameContributors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=100)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_contributors",
                        to="game_dev.game",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_games",
                        to="game_dev.member",
                    ),
                ),
            ],
            options={
                "unique_together": {("game", "member")},
            },
        ),
    ]
