# Generated by Django 5.1.14 on 2026-01-17 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game_dev", "0004_gamecontributors"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GameContributors",
            new_name="GameContributor",
        ),
    ]
