# Generated by Django 5.1.14 on 2025-12-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_dev", "0004_remove_games_itchembeddedid_alter_games_event_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="games",
            name="pathToMedia",
        ),
        migrations.AddField(
            model_name="games",
            name="pathToThumbnail",
            field=models.ImageField(null=True, upload_to="games/"),
        ),
    ]
