# Generated by Django 5.1.14 on 2025-11-28 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_dev", "0004_alter_event_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Art",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=200)),
                ("path_to_media", models.CharField(max_length=500)),
                ("active", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="ArtContributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=100)),
                (
                    "art",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributors",
                        to="game_dev.art",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="art_contributions",
                        to="game_dev.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Art Contributor",
                "verbose_name_plural": "Art Contributors",
                "unique_together": {("art", "member")},
            },
        ),
    ]
