# Generated by Django 5.1.14 on 2026-01-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_dev", "0004_gamecontributors"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameShowcase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_showcases",
                        to="game_dev.game",
                    ),
                ),
                (
                    "member",
                    models.ManyToManyField(
                        related_name="showcased_games",
                        to="game_dev.member",
                    ),
                ),
            ],
        ),
    ]
