# Generated by Django 5.1.14 on 2026-02-07 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_dev", "0004_alter_event_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Committee",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="game_dev.member",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("P", "President"),
                            ("VP", "Vice-President"),
                            ("SEC", "Secretary"),
                            ("TRE", "Treasurer"),
                            ("MARK", "Marketing"),
                            ("EV", "Events OCM"),
                            ("PRO", "Projects OCM"),
                            ("FRE", "Fresher Rep"),
                        ],
                        default="FRE",
                        max_length=9,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="member",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/"),
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "completion",
                    models.IntegerField(
                        choices=[
                            (1, "Work in Progress (Unplayable)"),
                            (2, "Playable - In Development"),
                            (3, "Beta - Stable but not Final"),
                            (4, "Completed"),
                        ],
                        default=1,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("hostURL", models.URLField(max_length=2083)),
                (
                    "itchEmbedID",
                    models.PositiveIntegerField(
                        blank=True,
                        default=None,
                        help_text="If game is stored on itch.io, please enter the itchEmbedID, i.e., 1000200",
                        null=True,
                    ),
                ),
                ("thumbnail", models.ImageField(null=True, upload_to="games/")),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="game_dev.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameShowcase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_showcases",
                        to="game_dev.game",
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameContributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=100)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_contributors",
                        to="game_dev.game",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_games",
                        to="game_dev.member",
                    ),
                ),
            ],
            options={
                "unique_together": {("game", "member")},
            },
        ),
    ]
