# Generated by Django 5.1.14 on 2026-01-21 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game_dev", "0005_gameshowcase"),
        ("game_dev", "0005_rename_gamecontributors_gamecontributor"),
    ]

    operations = []
