# Generated by Django 5.1.15 on 2026-01-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_dev', '0005_committee'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='role',
            field=models.CharField(choices=[('P', 'President'), ('VP', 'Vice-President'), ('SEC', 'Secretary'),
                                            ('TRE', 'Treasurer'), ('MARK', 'Marketing'), ('EV', 'Events OCM'),
                                            ('PRO', 'Projects OCM'), ('FRE', 'Fresher Rep')], default='FRE', max_length=9),
        ),
    ]
