# Generated by Django 5.1.14 on 2026-02-07 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_dev", "0005_committee_alter_member_profile_picture_game_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameshowcase",
            name="game",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_showcases",
                to="game_dev.game",
            ),
        ),
    ]
