# Generated by Django 5.1.14 on 2026-01-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_dev", "0005_alter_event_date_game_gameshowcase_gamecontributor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="isItch",
        ),
        migrations.AlterField(
            model_name="game",
            name="itchEmbedID",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                help_text="If game is stored on itch.io, please enter the itchEmbedID, i.e., 1000200",
                null=True,
            ),
        ),
    ]
