# Generated by Django 5.1.14 on 2025-12-13 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game_dev", "0005_remove_games_pathtomedia_games_pathtothumbnail"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Events",
            new_name="Event",
        ),
        migrations.RenameModel(
            old_name="Games",
            new_name="Game",
        ),
    ]
