# Generated by Django 5.1.14 on 2026-01-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_dev", "0006_merge_20260121_1416"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gameshowcase",
            name="member",
        ),
        migrations.AddField(
            model_name="game",
            name="itchEmbedID",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                help_text="If game is stored on itch.io, please enter the 7 digit long game id as its itchEmbedID, i.e., 1000200",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="hostURL",
            field=models.CharField(max_length=2083),
        ),
    ]
