# Generated by Django 5.1.15 on 2026-01-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_dev", "0006_rename_path_to_media_to_media"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="artcontributor",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="art",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="art",
            name="media",
            field=models.ImageField(upload_to="art/"),
        ),
        migrations.AddConstraint(
            model_name="artcontributor",
            constraint=models.UniqueConstraint(
                fields=("art", "member"), name="unique_art_member"
            ),
        ),
    ]
