# Generated by Django 5.1.14 on 2025-12-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_dev", "0006_rename_events_event_rename_games_game"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="description",
            field=models.TextField(),
        ),
    ]
