# Generated by Django 5.1.14 on 2026-01-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_dev", "0007_rename_pathtothumbnail_game_thumbnail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
