# Generated by Django 6.0 on 2026-01-30 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game_dev", "0005_alter_member_profile_picture"),
        ("game_dev", "0007_alter_artcontributor_unique_together_and_more"),
    ]

    operations = []
