# Generated by Django 5.1.14 on 2026-02-21 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_dev", "0007_art_artcontributor_artshowcase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="art",
            name="source_game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_artwork",
                to="game_dev.game",
            ),
        ),
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField(max_length=2083)),
                ("socialMediaUserName", models.CharField(blank=True, max_length=200)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_media_links",
                        to="game_dev.member",
                    ),
                ),
            ],
        ),
    ]
