# Generated by Django 5.1.15 on 2026-01-31 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_dev', '0005_alter_member_profile_picture'),
        ('game_dev', '0008_alter_event_date'),
    ]

    operations = [
    ]
