# Generated by Django 5.1.14 on 2026-02-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_dev", "0009_merge_20260131_1044"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="openstreetmap_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
