# Generated by Django 5.1.15 on 2026-01-31 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_dev', '0009_merge_20260129_2104'),
        ('game_dev', '0009_merge_20260131_1044'),
    ]

    operations = [
    ]
