# Generated by Django 5.1.14 on 2026-01-31 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_dev", "0009_merge_20260131_1044"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "socialMediaName",
                    models.CharField(
                        choices=[
                            ("TWITTER", "Twitter"),
                            ("FACEBOOK", "Facebook"),
                            ("INSTAGRAM", "Instagram"),
                            ("LINKEDIN", "LinkedIn"),
                            ("GITHUB", "GitHub"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("link", models.URLField(max_length=2083)),
                ("socialMediaUserName", models.CharField(blank=True, max_length=200)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_media_links",
                        to="game_dev.member",
                    ),
                ),
            ],
        ),
    ]
