# Generated by Django 5.1.15 on 2026-02-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_dev", "0009_merge_20260131_1044"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="itchGameEmbedID",
            field=models.PositiveBigIntegerField(
                blank=True,
                default=0,
                help_text="If a game has a web demo stored on itch.io, please enter the embed ID",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="itchGameHeight",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="game",
            name="itchGameWidth",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
