# Generated by Django 5.1.15 on 2026-01-21 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_dev', '0008_committee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='game_dev.member'),
        ),
    ]
