# Generated by Django 5.1.14 on 2026-02-03 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game_dev", "0010_merge_20260131_1118"),
        ("game_dev", "0010_socialmedia"),
    ]

    operations = []
