# Generated by Django 5.1.15 on 2026-02-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_dev', '0010_merge_20260131_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jam',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=75, unique=True, blank=False)),
                ('games', models.JSONField(default=list, blank=True)),
            ],
        ),
    ]
