# Generated by Django 6.0 on 2026-02-14 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game_dev", "0010_merge_20260131_1118"),
        ("game_dev", "0010_merge_20260131_1145"),
    ]

    operations = []
