# Generated by Django 5.1.14 on 2026-01-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_dev", "0009_remove_game_isitch_alter_game_itchembedid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="pathToThumbnail",
            new_name="thumbnail",
        ),
        migrations.AlterField(
            model_name="game",
            name="hostURL",
            field=models.URLField(max_length=2083),
        ),
    ]
