# Generated by Django 5.1.15 on 2026-02-13 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_dev', '0010_merge_20260131_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameshowcase',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_showcases', to='game_dev.game', unique=True),
        ),
    ]
