# Generated by Django 5.2.9 on 2026-02-04 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game_dev", "0008_art_showcase"),
        ("game_dev", "0010_merge_20260131_1145"),
    ]

    operations = []
