# Generated by Django 5.1.15 on 2026-01-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_dev', '0010_alter_committee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='role',
            field=models.CharField(choices=[('P', 'President'), ('VP', 'Vice-President'), ('SEC', 'Secretary'),
                                            ('TRE', 'Treasurer'), ('MARK', 'Marketing'), ('EV', 'Events OCM'),
                                            ('PRO', 'Projects OCM'), ('FRE', 'Fresher Rep')], default='FRE', max_length=9, unique=True),
        ),
    ]
