# Generated by Django 5.2.9 on 2026-02-04 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_dev", "0011_merge_0008_art_showcase_0010_merge_20260131_1145"),
    ]

    operations = [
        migrations.AddField(
            model_name="art",
            name="source_game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="art_pieces",
                to="game_dev.game",
            ),
        ),
        migrations.AlterConstraint(
            model_name="artshowcase",
            name="unique_artshowcase_per_art",
            constraint=models.UniqueConstraint(
                fields=("art",),
                name="unique_artshowcase_per_art",
                violation_error_message="Each art piece can only have one showcase.",
            ),
        ),
    ]
