# Generated by Django 5.1.15 on 2026-02-13 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_dev', '0011_alter_gameshowcase_game'),
        ('game_dev', '0012_remove_socialmedia_socialmedianame'),
    ]

    operations = [
    ]
