# Generated by Django 5.2.9 on 2026-02-04 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game_dev", "0010_merge_20260131_1118"),
        ("game_dev", "0012_art_source_game_and_more"),
    ]

    operations = []
