# Generated by Django 5.1.14 on 2026-02-17 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game_dev", "0010_event_openstreetmap_url"),
        ("game_dev", "0013_merge_20260214_1347"),
    ]

    operations = []
