# Generated by Django 5.1.15 on 2026-01-29 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_dev', '0006_alter_member_profile_picture'),
        ('game_dev', '0012_alter_committee_role'),
    ]

    operations = [
    ]
