# Generated by Django 5.2.9 on 2026-02-18 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game_dev", "0013_merge_20260204_1441"),
        ("game_dev", "0014_merge_20260214_1420"),
    ]

    operations = []
