# Generated by Django 5.1.15 on 2026-02-05 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game_dev", "0016_game_itchgameembedid_game_itchgameheight_and_more"),
        ("game_dev", "0017_merge_20260131_1118"),
    ]

    operations = []
