# Generated by Django 5.1.15 on 2026-02-14 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game_dev", "0019_alter_gameshowcase_game"),
        ("game_dev", "0021_merge_20260205_1434"),
    ]

    operations = []
