# Generated by Django 5.1.14 on 2026-02-07 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game_dev", "0020_merge_0010_merge_20260131_1118_0010_socialmedia"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="socialmedia",
            name="socialMediaName",
        ),
    ]
