# Generated by Django 5.1.15 on 2026-02-14 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_dev", "0022_merge_20260214_1112"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="itchGameEmbedID",
            field=models.PositiveBigIntegerField(
                blank=True,
                default=None,
                help_text="If a game has a web demo stored on itch.io, please enter the embed ID",
                null=True,
            ),
        ),
    ]
