# Generated by Django 5.1.15 on 2026-02-14 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_dev', '0019_alter_gameshowcase_game'),
        ('game_dev', '0023_remove_socialmedia_socialmedianame'),
    ]

    operations = [
    ]
