# Generated by Django 5.1.15 on 2026-02-14 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game_dev", "0024_alter_game_itchgameembedid"),
        ("game_dev", "0025_merge_20260214_1347"),
    ]

    operations = []
