# Generated by Django 5.1.15 on 2026-02-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_dev", "0026_merge_20260214_1420"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="itchGameEmbedID",
        ),
        migrations.AddField(
            model_name="game",
            name="itchGamePlayableID",
            field=models.PositiveBigIntegerField(
                blank=True,
                default=None,
                help_text="If a game is playable and has a web demo stored on itch.io, please enter the embed developer ID",
                null=True,
            ),
        ),
    ]
