# Generated by Django 5.1.15 on 2026-02-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_dev', '0027_remove_game_itchgameembedid_game_itchgameplayableid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='hostURL',
            field=models.URLField(blank=True, max_length=2083),
        ),
    ]
