# Generated by Django 5.1.15 on 2026-03-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_dev', '0028_alter_game_hosturl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='cover_image',
            new_name='coverImage',
        ),
        migrations.AddField(
            model_name='event',
            name='workshopLink',
            field=models.URLField(blank=True, max_length=2083),
        ),
    ]
