# Generated by Django 5.1.15 on 2026-02-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_dev', "0029_rename_cover_image_event_coverimage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='games',
            field=models.JSONField(blank=True, default=list, help_text='Only filled if event is a Game Jam'),
        ),
        migrations.AddField(
            model_name='event',
            name='jamID',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True, help_text="See documentation on how to find"),
        ),
    ]
