# Generated by Django 5.1.15 on 2026-03-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_dev', '0029_rename_cover_image_event_coverimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='itchGameHeight',
            field=models.PositiveBigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='itchGameWidth',
            field=models.PositiveBigIntegerField(blank=True, default=None, null=True),
        ),
    ]
