# Generated by Django 5.1.15 on 2026-03-01 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_dev', '0029_rename_cover_image_event_coverimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('media', models.ImageField(upload_to='art/')),
                ('active', models.BooleanField(default=True)),
                ('source_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_artwork', to='game_dev.game')),
            ],
        ),
        migrations.CreateModel(
            name='ArtContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='game_dev.art')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_contributions', to='game_dev.member')),
            ],
            options={
                'verbose_name': 'Art Contributor',
                'verbose_name_plural': 'Art Contributors',
                'constraints': [models.UniqueConstraint(fields=('art', 'member'), name='unique_art_member')],
            },
        ),
        migrations.CreateModel(
            name='ArtShowcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showcase', to='game_dev.art')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('art',), name='unique_artshowcase_per_art', violation_error_message='Each art piece can only have one showcase.')],
            },
        ),
    ]
