# Generated by Django 5.1.15 on 2026-04-04 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_dev', '0030_alter_game_itchgameheight_alter_game_itchgamewidth'),
        ('game_dev', '0030_art_artcontributor_artshowcase'),
    ]

    operations = [
    ]
