export const placeholderEvents = [
  {
    id: 1,
    name: "Event 1",
    time: "Monday 24th Oct 11:00am–4:00pm",
    description: "",
    publicationDate: "",
    date: "",
    startTime: "2:00",
    location: "",
    coverImage: "/landing_placeholder.png",
  },
  {
    id: 2,
    name: "Event 2",
    time: "Monday 24th Oct 11:00am–4:00pm",
    description: "",
    publicationDate: "",
    date: "",
    startTime: "2:00",
    location: "",
    coverImage: "/landing_placeholder.png",
  },
  {
    id: 3,
    name: "Event 3",
    time: "Monday 24th Oct 11:00am–4:00pm",
    description: "",
    publicationDate: "",
    date: "",
    startTime: "2:00",
    location: "",
    coverImage: "/landing_placeholder.png",
  },
  {
    id: 4,
    name: "Event 4",
    time: "Monday 24th Oct 11:00am–4:00pm",
    description: "",
    publicationDate: "",
    date: "",
    startTime: "2:00",
    location: "",
    coverImage: "/landing_placeholder.png",
  },
];

// Roughly reflects the game model but may need some finetuning.
export const placeholderGames = [
  {
    id: 1,
    name: "Game 1",
    description: "Game 1 description",
    completion: 1,
    active: true,
    hostURL: "/",
    itchEmbedID: "1",
    thumbnail: "/landing_placeholder.png",
    itchGamePlayableID: 0,
    itchGameWidth: 0,
    itchGameHeight: 0,
    event: 1,
  },
  {
    id: 2,
    name: "Game 2",
    description: "Game 2 description",
    completion: 1,
    active: true,
    hostURL: "/",
    itchEmbedID: "1",
    thumbnail: "/landing_placeholder.png",
    itchGamePlayableID: 0,
    itchGameWidth: 0,
    itchGameHeight: 0,
    event: 1,
  },
  {
    id: 3,
    name: "Game 3",
    description: "Game 3 description",
    completion: 1,
    active: true,
    hostURL: "/",
    itchEmbedID: "1",
    thumbnail: "/landing_placeholder.png",
    itchGamePlayableID: 0,
    itchGameWidth: 0,
    itchGameHeight: 0,
    event: 1,
  },
];
