import { MockArtwork } from "@/components/ui/GameArtCarousel";

export const mockGameArtworks: MockArtwork[] = [
  {
    id: 1,
    name: "Pixel Forest",
    image: "/landing_placeholder.png",
    sourceGameId: 1,
    gameName: "Minecraft",
  },
  {
    id: 2,
    name: "Cyber Arena",
    image: "/landing_placeholder.png",
    sourceGameId: 2,
    gameName: "Crownbreakers",
  },
  {
    id: 3,
    name: "Pixel Forest2",
    image: "/landing_placeholder.png",
    sourceGameId: 1,
    gameName: "Minecraft",
  },
  {
    id: 4,
    name: "Cyber Arena2",
    image: "/landing_placeholder.png",
    sourceGameId: 2,
    gameName: "Crownbreakers",
  },
  {
    id: 5,
    name: "Pixel Forest3",
    image: "/landing_placeholder.png",
    sourceGameId: 1,
    gameName: "Minecraft",
  },
  {
    id: 6,
    name: "Cyber Arena3",
    image: "/landing_placeholder.png",
    sourceGameId: 2,
    gameName: "Crownbreakers",
  },
  {
    id: 7,
    name: "Pixel Forest4",
    image: "/landing_placeholder.png",
    sourceGameId: 1,
    gameName: "Minecraft",
  },
  {
    id: 8,
    name: "Cyber Arena4",
    image: "/landing_placeholder.png",
    sourceGameId: 2,
    gameName: "Crownbreakers",
  },

  {
    id: 9,
    name: "Pixel Forest5",
    image: "/landing_placeholder.png",
    sourceGameId: 1,
    gameName: "Minecraft",
  },
  {
    id: 10,
    name: "Cyber Arena5",
    image: "/landing_placeholder.png",
    sourceGameId: 2,
    gameName: "Crownbreakers",
  },
  {
    id: 11,
    name: "Pixel Forest6",
    image: "/landing_placeholder.png",
    sourceGameId: 1,
    gameName: "Minecraft",
  },
  {
    id: 12,
    name: "Cyber Arena6",
    image: "/landing_placeholder.png",
    sourceGameId: 2,
    gameName: "Crownbreakers",
  },
  {
    id: 13,
    name: "Pixel Forest7",
    image: "/landing_placeholder.png",
    sourceGameId: 1,
    gameName: "Minecraft",
  },
  {
    id: 14,
    name: "Pixel Forest8",
    image: "/landing_placeholder.png",
    sourceGameId: 1,
    gameName: "Minecraft",
  },
  {
    id: 15,
    name: "Cyber Arena9",
    image: "/landing_placeholder.png",
    sourceGameId: 2,
    gameName: "Crownbreakers",
  },
];
